### ISSUE TITLE
Please add per-file licenses

### ISSUE THREAD

**Issue by petrcermak** [google/protorpc#14]
The Chromium project (www.chromium.org) pulls in protorpc indirectly through the catapult (https://github.com/catapult-project/catapult/) and gsutil (https://github.com/GoogleCloudPlatform/gsutil) source repositories. In order for Chromium to be pulled into various Linux source distributions there's a requirement that all of the third party files pass the Linux <tt>licensecheck</tt> utility. Currently there are many files in the protorpc repository missing per-file licenses. From a current run of <tt>licensecheck</tt>, they are:

```
$ licensecheck -r . | grep "No copyright"
./protorpc/google_imports.py: *No copyright* UNKNOWN
./protorpc/protorpc_test_pb2.py: *No copyright* GENERATED FILE
./protorpc/non_sdk_imports.py: *No copyright* UNKNOWN
./protorpc/webapp/google_imports.py: *No copyright* UNKNOWN
./ez_setup.py: *No copyright* UNKNOWN
./experimental/javascript/build.sh: *No copyright* UNKNOWN
./demos/quotas/backend/quotas/__init__.py: *No copyright* UNKNOWN
./demos/experimental/wsgi/services.py: *No copyright* UNKNOWN
./demos/tunes_db/server/appengine_config.py: *No copyright* UNKNOWN
```

We'd like to ask that per-file licenses be added to these files to make it easier to integrate protorpc not only into Chromium, but also Linux distributions in general. Thanks.

**Comment by craigcitro** [comment]
hi @petrcermak -- quick question: does chromium only pick up protorpc via apitools? as it happens, we've basically forked protorpc into apitools, in which case i can skip updating this repo, i think.

**Comment by petrcermak** [comment]
I'm afraid Chromium does **not** pick up protorpc via apitools. It picks protorpc up via gsutil:

https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/third_party/gsutil/third_party/protorpc/,
https://code.google.com/p/chromium/codesearch#chromium/src/tools/telemetry/third_party/gsutilz/third_party/protorpc/

**Comment by craigcitro** [comment]
ah -- but gsutil only includes protorpc because of apitools. :wink: 

so when gsutil updates, then chromium is OK?

**Comment by petrcermak** [comment]
I see. Yes, once gsutil reflects the fork, Chromium will be fine :+1:

**Comment by craigcitro** [comment]
score!

closing this for now.
